Repository RevRelay/RevRelay, pull requests merged in 2022-01, with the labels that each got.

#21 Search bar MVP
  src/App.js
  src/Components/Nav/NavSearchBar.js
  src/Components/Search.js
Labels: Docmnuetnation, Untested

#25 Comments added, Login splash removed, Themes fixed, Themes commented
  src/App.js
  src/Components/Nav.js
  src/Components/NoAuth/Auth.css
  src/Components/NoAuth/LandscapeGen.js
  src/Components/NoAuth/Login.js
  src/Components/NoAuth/LoginSplash.js
  src/Components/NoAuth/Register.js
  src/Components/NoAuth/RegisterConfig.js
Labels: Untested, Undocumented

#24 Rph add new post and load all posts
  package-lock.json
  src/App.js
  src/Components/NoAuth/Auth.css
  src/Components/Page.js
  src/Components/Posts.js
Labels: Untested, Undocumented

#27 User info axios
  package-lock.json
  package.json
  src/API/UserAPI.js
  src/Components/UserInfo/UserInfo.js
  src/Components/UserInfo/UserInfoEntryElement.js
  src/parseJWT.js
Labels: Test, Docmnuetnation

#28 2 PASSWORD FIELDS!!! WOOO. Also password fields hidden
  src/Components/Nav.js
  src/Components/Nav/Nav.js
  src/Components/NoAuth/Login.js
  src/Components/NoAuth/Register.js
Labels: Docmnuetnation

#37 Rph chat integrated
  src/App.js
  src/Components/Chat.js
  src/Components/Client.js
  src/index.css
Labels: Documentation

#46 Show password button
  src/Components/Library/FormField.js
  src/Components/NoAuth/Login.js
  src/Components/NoAuth/Register.js
  src/Components/UserInfo/ChangePassword.js
Labels: Documentation

#43 Groups pages settings
  package-lock.json
  package.json
  src/API/PageAPI.js
  src/API/UserAPI.js
  src/App.js
  src/Components/Client.js
  src/Components/Group/AddMember.js
  src/Components/Group/CreateGroup.js
  src/Components/Page.js
  src/Components/Page/FriendsTab.js
  src/Components/Page/PageSetting.js
  src/Components/Posts.js
Labels: Untested, Undocumented

#60 Fixed group bugs
  src/API/APIQuery.js
  src/API/PageAPI.js
  src/API/UserAPI.js
  src/Components/Chat.js
  src/Components/Client.js
  src/Components/HomeSplash/Home.js
  src/Components/Page.js
  src/Components/Page/FriendsTab.js
  src/Components/Page/PageSetting.js
  src/Components/Posts.js
Labels: Untested
